name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          #start: npm start
          #wait-on: 'http://localhost:3000'
          browser: chrome
          # Run only API tests
          spec: cypress/e2e
          # Pass custom environment variables
          env: grepTags=@smoke
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
