name: Run cypress Tests

on:
  repository_dispatch:
    types: [run-tests]

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          record: true
          with:
          browser: chrome
          # Run only API tests
          spec: cypress/e2e
          # Pass custom environment variables
          env: grepTags=@smoke
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}